### ISSUE TITLE
Trying to create application with component ends up with 404 Not Found error

### ISSUE THREAD

**Issue by yftacherzog** [konflux-ci/konflux-ci#150]
Not sure what are the scenarios in which this is happening. Need to figure out how to recreate it.

Following the discussion below, we should have this error documented on our troubleshooting guide, telling users that they need to verify they install image-controller.

**Comment by ralphbean** [comment]
One thing we found is that the error came from the UI attempting to POST to create an `imagerepository`, but our installer here doesn't install the image controller (on purpose). If it's a bug, it's a bug in the UI (or the version of the UI that the installer installed) where it tries to create image repositories but it shouldn't.

It's complex - because the UI was recently taught to create imagerepositories - but it should only do that _if_ the image-controller is installed.

**Comment by gbenhaim** [comment]
The import flow using the UI will only work when deploying the image-controller. I think that until we remove the hard dependency of the UI on the image controller, we would have to be more clear about the need to run `deploy-image-controller.sh` as part of installing the cluster. This can be done by updating the readme and mention it  alongside the other commands which are needed for installing Konflux https://github.com/konflux-ci/konflux-ci?tab=readme-ov-file#bootstrapping-the-cluster

**Comment by yftacherzog** [comment]
Yes. I tend to think that this is what we missed yesterday.
When I tested it on my setup at that time, I also saw this issue, but in hindsight, I realize that the last thing I tested locally was the no-UI flow and that's the reason I didn't have image-controller installed. Once I recreated the cluster according to the with-UI flow everything was working.
