### ISSUE TITLE
update build pipeline fails CI

### ISSUE THREAD

**Issue by yftacherzog** [konflux-ci/konflux-ci#518]
Need to figure out why this PR fails
https://github.com/konflux-ci/konflux-ci/pull/509

**Comment by psturc** [comment]
So the test fails due to insufficient cpu/memory in cluster, see ([this comment](https://github.com/konflux-ci/konflux-ci/pull/509#issuecomment-2402055096))

I've got [this workaround](https://github.com/psturc/konflux-ci/pull/14/files#diff-fd17c12f6a9db21ecea8c3d688e76cad475c81ac6b6ba0ef6eaa958c5bee288eR25-R35), but now the CI fails on:

```
***"level":"info","ts":"2024-10-10T16:05:21Z","logger":"controllers.build pipeline","caller":"buildpipeline/buildpipeline_adapter.go:333","msg":"Finished processing of unsuccessful build PLR","buildpipelineRun":***"name":"***-upstream-uwjx-on-pull-request-vtcml","namespace":"user-ns2"***,"application":"user-ns2/***-upstream","statusCondition":***"conditions":[***"type":"Succeeded","status":"False","lastTransitionTime":"2024-10-10T16:05:21Z","reason":"CouldntGetTask","message":"Pipeline user-ns2/***-upstream-uwjx-on-pull-request-vtcml can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task \"\": error requesting remote resource: error getting \"bundleresolver\" \"user-ns2/bundles-16f66f464bf3bddf3338f38a42ac90c2\": cannot retrieve the oci image: Get \"https://registry-service.kind-registry/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"***],
```

**Comment by psturc** [comment]
I tried to [mount the ca-bundle to pipelines-controller](https://github.com/psturc/konflux-ci/pull/14/files#diff-85c8514b34d569ea1ce56171eb7d02533b44f7c69e77b4610f10309329193c72R45-R68), but it still didn't work

I also tried to add the ca bundle to the `config-registry-cert` as described [here](https://github.com/tektoncd/pipeline/pull/2787/files#diff-162b45a313f5f057a233411edbe31e72a13185f4df0ae0e1af2c13521bc05d5aR267), but still no luck

It's strange because when I try to curl the registry endpoint from some pod running on the cluster, it works just fine:
```bash
bash-4.4$ curl -I https://registry-service.kind-registry/v2/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
bash-4.4$ 
bash-4.4$ # Using the ca-bundle:
bash-4.4$ curl -I https://registry-service.kind-registry/v2/ --cacert /tmp/cert.crt 
HTTP/2 200 
content-type: application/json; charset=utf-8
docker-distribution-api-version: registry/2.0
x-content-type-options: nosniff
content-length: 2
date: Fri, 11 Oct 2024 14:16:49 GMT

bash-4.4$
```

**Comment by yftacherzog** [comment]
I'm still not what's causing it.
If this is a change we did then how come it passed CI for that change.
It doesn't look flaky -- it seems broken altogether.

I checked out code from a couple of days before PRs started failing and created a PR with that code.
The logs still look similar.

I wonder if it might be something related to the infrastructure rather than to our codebase.

**Comment by yftacherzog** [comment]
I see that GitHub recently updated their ubuntu-latest to `ubuntu-24.04`.
Can you try on your fork to replace within the sanity-check workflow ``ubuntu-latest` to `ubuntu-22.04`?

I think this might not take effect on the same PR though. You might need to merge it and then test on some other change.

Inside the workflow logs you should see:

```
Current runner version: '2.320.0'
Operating System
  Ubuntu
  22.04.5
  LTS
```

**Comment by yftacherzog** [comment]
@psturc, as you mentioned over chat, there seem to be 2 different issues. One that is failing that specific PR and another that fails all other PRs. I'll open a new issue for that.

**Comment by yftacherzog** [comment]
@psturc what's the current state with this one? Is this something we can collaborate on?

**Comment by psturc** [comment]
@yftacherzog I think we have 2 options:

1. Figure out how to make tekton controller trust the ca-bundle (the issue described [here](https://github.com/konflux-ci/konflux-ci/issues/518#issuecomment-2407516190)). I've already spent quite a lot of time on investigating that and I would need a hint, because currently I'm out of ideas.
2. Instead of pushing the updated Pipeline and Task to local registry, I could update the script to push them to quay.io instead, then we would not hit the issue described in previous point.

**Comment by yftacherzog** [comment]
I'll try looking into this in the coming days. Thank you for the work so far!

**Comment by psturc** [comment]
resolved with https://github.com/konflux-ci/konflux-ci/pull/509/commits/8ec16a145296f9d875cb7026ddfb5bfb2190649a

**Comment by yftacherzog** [comment]
Thank you @psturc. I see that the next renovate PR for this package was also merged automatically after this change.
Nicely done!
