### ISSUE TITLE
pipeline-docker-build fails to update

### ISSUE THREAD

**Issue by yftacherzog** [konflux-ci/konflux-ci#846]
See #827

**Comment by yftacherzog** [comment]
@psturc Hi, do you think this is something that can be taken within your team (not super urgent)?
It's failing for the last couple of weeks. I haven't tried to investigate yet why it's failing again.

**Comment by psturc** [comment]
Hi @yftacherzog, the E2E test image required an update, because one test became outdated. I fixed it with [this commit](https://github.com/konflux-ci/konflux-ci/pull/827/commits/9b4eaaebd540f3315ccddccd8045cd3dd3b5e12f)

In the future, it'd be good to have a process for updating E2E test image automated. [KFLUXDP-16](https://issues.redhat.com/browse/KFLUXDP-16) should cover it.

**Comment by yftacherzog** [comment]
Amazing. Thank you!
